### ISSUE TITLE
`getDurationString` - do not include hours if zero

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#686]
If duration is less than an hour - do not include hours in the string.

ACTUAL: `00h 01m 00s`
EXPECTED: `01m 00s`

**Comment by tomaskikutis** [comment]
Sometimes it's desired to include zeroes for UI alignment reasons. I'd then need a parameter that would determine if duration string is shortened to omit zeroes or not.

**Comment by dzonidoo** [comment]
https://github.com/superdesk/superdesk-ui-framework/pull/688

**Comment by tomaskikutis** [comment]
I see you didn't add a parameter I requested in the previous comment. Do add it

**Comment by dzonidoo** [comment]
https://github.com/superdesk/superdesk-ui-framework/pull/698

**Comment by tomaskikutis** [comment]
I may have not been clear about the extra parameter. It's not about `zeroPad` - that should always apply. I meant to print hours even if it's `00h`. Could you adjust it @dzonidoo?

WITHOUT PARAMETER: `15m 54s`
WITH PARAMETER: `00h 15m 54s`

**Comment by dzonidoo** [comment]
now its clear... Im on it

**Comment by IvanJelicSF** [comment]
Hey, it seems that we might have lost some things in transmission, so let me summarize that needs to be achieved. We are not displaying hours if they are zero always, that stays the same. We will display minutes even if they are zero, therefore, we should always have minutes, starting from 00m to 59m. We are also forcing two digits everywhere, even if the first one is 0 (01 instead of 1).

So, we might want two parameters then, one for minutes and one for hours. We do not display both minutes and hours if they are zero by default. If `HOURS PARAMETER`, we show 00h, if `MINUTES PARAMETER`, we show 00m. 

Our current requirement would mean that we are always going without `HOURS PARAMETER`, but with `MINUTES PARAMETER`. In case things change somewhere (aka client wants something else), we just switch parameters, although we will probably never have a situation to have `HOURS PARAMETER` without `MINUTES PARAMETER`, but who knows :) 

We might even want to add something like `LEADING ZERO`, so we can have both 00 and 0, depending on the situation. That would mean using `MINUTES PARAMETER` and `LEADING ZERO` to achieve our current goal.

Thanks!

**Comment by dzonidoo** [comment]
https://github.com/superdesk/superdesk-ui-framework/pull/703
